The arithmetic of a curve over a number field $k$ encapsulates all of its $\overline{k}$ points together with the action of the absolute Galois group. Points on curves can also be viewed as divisors, and this dual identity gives powerful geometric tools to approach the problem. My research in this direction aims to leverage these geometric tools to organize and perhaps even understand $\overline{k}$ points on a curve.

The article [Isolated and parameterized points on curves](https://arxiv.org/abs/2406.14353), written jointly with Isabel Vogt, gives an introduction to these ideas with several examples.

#### Talks

Colloquium at CRM, April 2024:

```{=html}
<iframe width="560" height="315" src="https://www.youtube.com/embed/X7t52p5Q4lQ" title="Colloquium at CRM, April 2024" allowfullscreen style="border:none; max-width:100%;"></iframe>
```

Workshop at ICERM, June 2025: [video](https://icerm.brown.edu/video_archive/4172)

#### Papers

- *Number fields generated by points in linear systems on curves*, joint with Irmak Balçik, Stephanie Chan, and Yuan Liu — [arXiv](https://arxiv.org/pdf/2503.07846)
- *Superelliptic degree sets over Henselian fields*, by Alex Galarraga and Alex Wang — [arXiv](https://arxiv.org/abs/2511.15951)
- *Degrees of points on varieties over Henselian fields*, joint with Brendan Creutz — [arXiv](https://arxiv.org/abs/2306.01267)
- *On the level of modular curves that give rise to isolated j-invariants*, joint with Abbey Bourdon, Ozlem Ejder, Yuan Liu and Frances Odumodu — [arXiv](https://arxiv.org/abs/1808.04520)
