---
title: "Research"
---

Complete lists of my preprints and publications can be found on my [arXiv](https://arxiv.org/a/viray_b_1.html) page and on my [MathSciNet author page](https://mathscinet.ams.org/mathscinet/MRAuthorID/890397) (subscription required). 

*Under construction: research descriptions in progress*
<!-- ## Arithmetic geometry

My research lies in arithmetic geometry.  As the name suggests, this research area sits at the interface of two fields: *arithmetic* (the study of integers and rational numbers, which is heavily influenced by the prime numbers); and *geometry* (the study of curves, surfaces, and higher-dimensional shapes).  These distinct areas are brought together through the study of solutions to polynomial equations, i.e., the study of varieties.  

A guiding philosophy of this area is *Geometry controls arithmetic*. For example, since the geometry of the above variety on the right is more complicated than the one on the left (the one on the right has larger genus, which is seen by the increased 'curviness' of the graph), the arithmetic properties of the variety on the right *should* also be more complicated.  This turns out to be true in two senses: the rational points (i.e., the solutions with all coordinates in Q) on the variety on the right are sparser than those on the left, and it is harder to characterize all the rational points on the variety on the right.

This philosophy provides a powerful perspective, but many mathematical questions need to be answered to make it precise.  Which aspects of the geometry are important for a given arithmetic property? When we try to understand finer arithmetic properties, do we need to delve deeper into the geometry? What are the limitations of this philosophy? -->


### Algebraic points on curves ###

The arithmetic of a curve over a number field $k$ encapsulates all of its $\overline{k}$ points together with the action of the absolute Galois group. Points on curves can also be viewed as divisors, and this dual identity gives powerful geometric tools to approach the problem. My research in this direction aims to leverage these geometric tools to organize and perhaps even understand $\overline{k}$ points on a curve.

The article [Isolated and parameterized points on curves](https://arxiv.org/abs/2406.14353), written jointly with Isabel Vogt, gives an introduction to these ideas with several examples.

Here are some talks I've given on these concepts:

* Colloquium at CRM in April 2024 {{< video https://www.youtube.com/watch?v=X7t52p5Q4lQ >}} 
* Workshop at ICERM in June 2025 [video](https://icerm.brown.edu/video_archive/4172)

and here are my and my students' research papers in this direction:

* *Number fields generated by points in linear systems on curves*, joint with Irmak Balçik, Stephanie Chan, and Yuan Liu
[{{< ai arxiv >}}](https://arxiv.org/pdf/2503.07846)   
* *Superelliptic degree sets over Henselian fields*, by Alex Galarraga and Alex Wang [{{< ai arxiv >}}](https://arxiv.org/abs/2511.15951)
* *Degrees of points on varieties over Henselian fields*, joint with Brendan Creutz [{{< ai arxiv >}}](https://arxiv.org/abs/2306.01267)
* *On the level of modular curves that give rise to isolated j-invariants*, joint with Abbey Bourdon, Ozlem Ejder, Yuan Liu and Frances Odumodu [{{< ai arxiv >}}](https://arxiv.org/abs/1808.04520)

### The Brauer-Manin obstruction: capturing subgroups and behavior under extensions ###

In 2022, I gave a lecture series at the Park City Mathematics Institute (PCMI) Graduate Summer School: Number Theory Informed by Computation. The lecture series was titled: *Rational points on varieties and the Brauer-Manin obstruction*, and focused on (my perspective on) how the feedback loop between computation and theory currently manifests in the study of rational points and the Brauer-Manin obstruction. My [lecture notes](https://arxiv.org/abs/2303.17796) give an introduction to the Brauer-Manin obstruction, so-called "capturing" subgroups of the Brauer-Manin obstruction, and questions concerning the Brauer-Manin obstruction over extensions.

{{< video https://www.youtube.com/watch?v=m4J5yBo-f3Y&t=0s >}}
{{< video https://www.youtube.com/watch?v=NSH-yXErpxs >}}
{{< video https://www.youtube.com/watch?v=KWLeJUX8kX0&t=0s >}}

Here are my and my students' research papers in this direction:

**Capturing subgroups of the Brauer-Manin obstruction**

* *Brauer-Manin obstructions requiring arbitrarily many Brauer classes*, joint with Jennifer Berg, Carlo Pagano, Bjorn Poonen, Michael Stoll, Nicholas Triantafillou, and Isabel Vogt [{{< ai arxiv >}}](https://arxiv.org/abs/2309.05931)
* *The $d$-primary Brauer-Manin obstruction for curves*, joint with Brendan Creutz and Felipe Voloch [{{< ai arxiv >}}](https://arxiv.org/abs/1711.00569)
* *Degree and the Brauer-Manin obstruction*, joint with Brendan Creutz, with an appendix by Alexei Skorobogatov [{{< ai arxiv >}}](https://arxiv.org/abs/1703.02187)

**The Brauer-Manin obstruction under extensions**

* *On the Hasse principle for conic bundles over even extensions* by Sam Roven and Alex Wang [{{< ai arxiv >}}](https://arxiv.org/abs/2508.07564)
* *Quartic del Pezzo surfaces without quadratic points*, joint with Brendan Creutz [{{< ai arxiv >}}](https://arxiv.org/abs/2408.08436)
* *Quadratic points on intersections of two quadrics*, joint with Brendan Creuz [{{< ai arxiv >}}](https://arxiv.org/abs/2106.08560)
* *Persistence of the Brauer-Manin obstruction on cubic surfaces*, joint with Carlos Rivera [{{< ai arxiv >}}](https://arxiv.org/abs/2111.03546)

### Rational points on surfaces ###

In 2015, I gave a lecture series at the Arizona Winter School about explicit computation of the Brauer group and the Brauer-Manin obstruction on surfaces. Lecture notes are available on the [Arizona Winter School website](https://swc-math.github.io/aws/2015/index.html).

{{< video https://www.youtube.com/watch?v=CxIojT0gmCc&t=0s >}}
{{< video https://www.youtube.com/watch?v=fAJnoUPCuVg&t=0s >}}
{{< video https://www.youtube.com/watch?v=70kZzHZLfv8 >}}
{{< video https://www.youtube.com/watch?v=EH6lZASFbus&t=0s >}}
{{< video https://www.youtube.com/watch?v=uI0GsizXcgo >}}

Here are my research papers in this direction:

* *Insufficiency of the Brauer-Manin obstruction for Enriques surfaces*, joint with Francesca Balestrieri, Jennifer Berg, Michelle Manes, and Jennifer Park [{{< ai arxiv >}}](https://arxiv.org/abs/1501.04974)
* *Unramified Brauer classes on cyclic covers of the projective plane*, joint with Colin Ingalls, Andrew Obus, and Ekin Ozman [{{< ai arxiv >}}](https://arxiv.org/abs/1310.8005)
* *On Brauer groups of double covers of ruled surfaces*, joint with Brendan Creutz [{{< ai arxiv >}}](https://arxiv.org/abs/1306.3251)
* *Two torsion in the Brauer group of a hyperelliptic curve*, joint with Brendan Creutz [{{< ai arxiv >}}](https://arxiv.org/abs/1403.2924)
* *Vertical Brauer groups and del Pezzo surfaces of degree $$*, joint with Anthony Várilly-Alvarado [{{< ai arxiv >}}](https://arxiv.org/abs/1210.0920)
* *Higher dimensional analogs of Châtelet surfaces*, joint with Anthony Várilly-Alvarado [{{< ai arxiv >}}](https://arxiv.org/abs/1101.5453)
* *Failure of the Hasse principle for Enriques surfaces*, joint with Anthony Várilly-Alvarado [{{< ai arxiv >}}](https://arxiv.org/abs/1008.0596)
* *Failure of the Hasse principle for Châtelet surfaces in characteristic $2$* [{{< ai arxiv >}}](https://arxiv.org/abs/0902.3644)
